# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: ubuntu-latest

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'sonarqube-scanner-maven/maven-multimodule/pom.xml'
    options: '-ntp -B'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    codeCoverageToolOption: 'jaCoCo'
#    codeCoverageClassFilesDirectories: 
#    codeCoverageSourceDirectories: 
    codeCoverageFailIfEmpty: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: 'latest'
    isJacocoCoverageReportXML: true
#    codeCoverageClassFilter: 
- task: CmdLine@2
  inputs:
    script: 'dir'